name: humomni
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchaudio
  - pip:
      - transformers>=4.45,<5
      - scikit-learn
      - peft
      - qwen-omni-utils
      - python-dotenv
      - datasets
      - huggingface_hub
      - accelerate
      - librosa
      - soundfile
      - pandas
      - numpy
      - tqdm
      - pyyaml
      - openai-whisper
      - sentence-transformers
      - dashscope
      - python-dotenv
